name = "LeanReach"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanReach", "leanreach", "leanreach_tests"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[lean_lib]]
name = "LeanReach"

[[lean_lib]]
name = "Tests"

[[lean_exe]]
name = "leanreach"
root = "Main"
supportInterpreter = true

[[lean_exe]]
name = "leanreach_tests"
root = "Tests.Main"
supportInterpreter = true
