name = "LeanReach"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanReach", "leanreach"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[lean_lib]]
name = "LeanReach"

[[lean_exe]]
name = "leanreach"
root = "Main"

[[lean_exe]]
name = "leanreach_tests"
root = "Tests.Smoke"

[[lean_exe]]
name = "leanreach_integration_tests"
root = "Tests.Integration"
