name: Mathlib Tests

on:
  push:
    branches: [mathlib-tests]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: leanprover/lean-action@v1
        with:
          build-args: "--wfail"
          lake-package-directory: Tests/Mathlib
          use-mathlib-cache: true
      - name: Run Mathlib integration tests
        working-directory: Tests/Mathlib
        run: lake exe leanreach_mathlib_tests
